name: C++ CI

on:
  push:
    branches: [ vtk9 ]

  pull_request:
    branches: [ vtk9 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install gtest manually
      run: sudo apt-get install -y libgtest-dev libeigen3-dev cmake && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && ls -a && cd lib && sudo cp *.a /usr/lib
    - name: configure
      run: cd cpp && mkdir build && cd build && cmake -DTESTPSFLIB=ON ..
    - name: make
      run: cd cpp/build && make
    - name: Run Test
      run: cd cpp/build && ./runPsfLibTests
